#!/usr/bin/env bash
# Husk — production installer for Linux
# Installs deps, builds native modules, registers as a real desktop app
# (icon + .desktop entry). Launchable from app menu, dock, favorites.
set -e

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_ID="husk"
APP_NAME="Husk"

BIN_DIR="$HOME/.local/bin"
DESKTOP_DIR="$HOME/.local/share/applications"
ICON_DIR="$HOME/.local/share/icons/hicolor/256x256/apps"
WRAPPER="$BIN_DIR/$APP_ID"
DESKTOP_FILE="$DESKTOP_DIR/$APP_ID.desktop"
ICON_FILE="$ICON_DIR/$APP_ID.png"

C_OK='\033[0;32m'; C_INFO='\033[0;36m'; C_WARN='\033[1;33m'; C_RST='\033[0m'
info()    { echo -e "${C_INFO}▸${C_RST} $1"; }
ok()      { echo -e "${C_OK}✓${C_RST} $1"; }
warn()    { echo -e "${C_WARN}!${C_RST} $1"; }

cd "$APP_DIR"

# ─── 1. Dependencies ──────────────────────────────────────────────
if [ ! -d node_modules ] || [ ! -f node_modules/node-pty/build/Release/pty.node ]; then
    info "Installing Node dependencies..."
    npm install --no-audit --no-fund
    info "Rebuilding node-pty for Electron's Node ABI..."
    npx --yes @electron/rebuild -f -w node-pty
    ok "Dependencies installed"
else
    ok "Dependencies already installed"
fi

# ─── 2. Sandbox helper (one-time secure-mode prep) ────────────────
SANDBOX_BIN="$APP_DIR/node_modules/electron/dist/chrome-sandbox"
if [ -e "$SANDBOX_BIN" ]; then
    OWNER=$(stat -c '%U' "$SANDBOX_BIN" 2>/dev/null || echo "")
    PERMS=$(stat -c '%a' "$SANDBOX_BIN" 2>/dev/null || echo "")
    if [ "$OWNER" = "root" ] && [ "$PERMS" = "4755" ]; then
        ok "Sandbox helper is setuid root (secure mode)"
    else
        warn "Sandbox helper not setuid — app will run with --no-sandbox (fine for personal use)"
        info "  To enable secure sandbox: sudo chown root:root \"$SANDBOX_BIN\" && sudo chmod 4755 \"$SANDBOX_BIN\""
    fi
fi

# ─── 3. Wrapper script (launcher target) ──────────────────────────
mkdir -p "$BIN_DIR"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by Husk install.sh — do not edit by hand
cd "$APP_DIR"
exec ./run.sh
EOF
chmod +x "$WRAPPER"
ok "Wrapper installed: $WRAPPER"

# ─── 4. Icon ──────────────────────────────────────────────────────
mkdir -p "$ICON_DIR"
cp "$APP_DIR/installer/husk-icon.png" "$ICON_FILE"
ok "Icon installed: $ICON_FILE"

# ─── 5. Desktop entry ─────────────────────────────────────────────
mkdir -p "$DESKTOP_DIR"
cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=$APP_NAME
GenericName=AI Agent Shell
Comment=Visual desktop shell for Claude Code and other terminal AI agents
Icon=$ICON_FILE
Exec=$WRAPPER
Terminal=false
Categories=Development;Utility;Network;
StartupNotify=true
StartupWMClass=Husk
Keywords=ai;claude;agent;chat;terminal;husk;
EOF
chmod +x "$DESKTOP_FILE"
ok "Desktop entry installed: $DESKTOP_FILE"

# ─── 5b. Bootstrap PAI (reasoning + skills) into ~/.claude/ ────────
# Husk ships with a copy of PAI (Personal AI Infrastructure) by Daniel
# Miessler. We copy the framework, agents, hooks, lib, skills, and a
# CLAUDE.md template into ~/.claude/ on first install so the agent has a
# rich reasoning + thinking layer out of the box. Existing files are
# never overwritten — if you have your own ~/.claude/, we only add what's
# missing.
PAI_BUNDLE="$APP_DIR/libs/pai"
CLAUDE_DIR="$HOME/.claude"
if [ -d "$PAI_BUNDLE" ]; then
    info "Bootstrapping PAI into $CLAUDE_DIR (only adds missing files)..."
    mkdir -p "$CLAUDE_DIR"
    if [ ! -f "$CLAUDE_DIR/CLAUDE.md" ]; then
        cp "$PAI_BUNDLE/CLAUDE.md.template" "$CLAUDE_DIR/CLAUDE.md" 2>/dev/null \
            || cp "$PAI_BUNDLE/CLAUDE.md" "$CLAUDE_DIR/CLAUDE.md" 2>/dev/null || true
        ok "Installed CLAUDE.md (you can edit it any time)"
    fi
    for SUBDIR in PAI agents hooks lib skills; do
        if [ -d "$PAI_BUNDLE/$SUBDIR" ]; then
            if [ ! -d "$CLAUDE_DIR/$SUBDIR" ]; then
                cp -r "$PAI_BUNDLE/$SUBDIR" "$CLAUDE_DIR/$SUBDIR"
                ok "Installed $SUBDIR/"
            else
                # Merge in any missing items without overwriting user data.
                cp -rn "$PAI_BUNDLE/$SUBDIR/." "$CLAUDE_DIR/$SUBDIR/" 2>/dev/null || true
            fi
        fi
    done
    [ ! -f "$CLAUDE_DIR/blocklist.json" ] && cp "$PAI_BUNDLE/blocklist.json" "$CLAUDE_DIR/blocklist.json" 2>/dev/null || true
    [ ! -f "$CLAUDE_DIR/statusline-command.sh" ] && cp "$PAI_BUNDLE/statusline-command.sh" "$CLAUDE_DIR/statusline-command.sh" 2>/dev/null && chmod +x "$CLAUDE_DIR/statusline-command.sh" || true
    ok "PAI ready"
fi

# ─── 6. Refresh system caches ─────────────────────────────────────
if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "$DESKTOP_DIR" 2>/dev/null || true
    ok "Desktop database refreshed"
fi
if command -v gtk-update-icon-cache >/dev/null 2>&1; then
    gtk-update-icon-cache -tf "$HOME/.local/share/icons/hicolor" 2>/dev/null || true
    ok "Icon cache refreshed"
fi

# ─── 7. Add to GNOME favorites (best-effort, opt-in) ──────────────
if command -v gsettings >/dev/null 2>&1; then
    CURRENT=$(gsettings get org.gnome.shell favorite-apps 2>/dev/null || echo "")
    if [ -n "$CURRENT" ] && ! echo "$CURRENT" | grep -q "$APP_ID.desktop"; then
        echo
        read -p "Pin Husk to GNOME favorites bar? [Y/n]: " -r REPLY
        if [[ -z "$REPLY" || "$REPLY" =~ ^[Yy]$ ]]; then
            NEW=$(echo "$CURRENT" | sed "s/]/, '$APP_ID.desktop']/")
            gsettings set org.gnome.shell favorite-apps "$NEW" 2>/dev/null && ok "Pinned to favorites" || warn "Could not pin (non-GNOME?)"
        fi
    fi
fi

echo
echo -e "${C_OK}═══════════════════════════════════════════════════════${C_RST}"
echo -e "${C_OK}  Husk installed${C_RST}"
echo -e "${C_OK}═══════════════════════════════════════════════════════${C_RST}"
echo
echo "  Launch: open the Activities / Apps menu, search 'Husk'"
echo "  Or run: $WRAPPER"
echo
echo "  Uninstall:  ./uninstall.sh"
echo
